id: P57766D4F
initial_creation_type: input
source_metadata:
  title: Calling the Guru from Afar
  language: es
  description: 'Devotional texts belonging to the genre of Calling the Guru from Afar
    (bla ma rgyang ''bod):'
  volume:
    b8787788567f467682ccef157ceff7c0:
      title: Spontaneous Advice Connected with a Prayer
      parent: Advice
    aa2951bf94f846a89fc0da310ec5761f:
      title: 'The Excellent Path of Supreme Great Bliss: A Prayer for Calling the
        Guru from Afar'
      parent: Prayers
    7e309c5a202f4bb79ad93e65a49b7816:
      title: Calling the Guru From Afar
      parent: Prayers
    983a8d2ba7824fbe881254d0a994f1db:
      title: 'Nectar Shower of Blessings: A Song of Yearning Devotion Recalling the
        Everpresent Gurus'
      parent: Prayers
    336df11eb98848558abb24e81193aee0:
      title: 'Spontaneous Song of the Genuine Nature: A Prayer of Calling the Guru
        from Afar'
      parent: Prayers
    e4761f274bd44ac9b0655aacd784cf27:
      title: A Song of Calling the Guru from Afar
      parent: Prayers
    234f174993c043598ab654bac0ae9720:
      title: 'Calling the Guru From Afar: A Prayer to Pierce the Heart with Devotion'
      parent: Prayers
    a4fcdb55054545f18209fd5bfe666413:
      title: 'An Envoy for Swiftly Invoking the Blessings of Definitive Meaning: Calling
        the Great Omniscient Jonangpa from Afar'
      parent: Prayers
    9c13e3f5d92d441cbc3527ef81bd46e9:
      title: 'Calling the Guru from Afar: A Prayer to Jigme Lingpa'
      parent: Prayers
    e6410a3ef8b944d4afab69bbe5a251b9:
      title: 'Dispelling the Anguish of Existence and Quiescence: A Prayer of Calling
        the Guru from Afar'
      parent: Prayers
    fa506e14ba4b48b8bc8c6e4b8f61355c:
      title: Prayer and Call from Afar to the Great Omniscient One
      parent: Prayers
    288f533e0ea942d996488241377ac00d:
      title: 'Gyang Lu: A Song of Calling from Afar'
      parent: Prayers
    e4771cc752b346a4b897a21b2ece9ec0:
      title: 'Luminous Clouds of Spontaneous Song: A Prayer to Call the Guru from
        Afar'
      parent: Prayers
    a8adf60dd1f34939bfebe8ec91ad2cbb:
      title: Calling the Guru from Afar
      parent: Prayers
created_at: '2022-03-01T03:10:18.230851'
last_modified_at: '2022-03-01T03:10:18.230854'
